name = "gramps"
version = "6.0.0"
description = "A Gleam HTTP and WebSocket helper library"

licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "gramps" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 5.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.1 and < 2.0.0"
